language: objective-c

before_install:
  - rvm use system
  - sudo gem install cocoapods -v '0.39.0'

osx-image: xcode7.3
xcode_workspace: Orlando Walking Tours.xcworkspace
xcode_sdk: iphonesimulator9.2
podfile: Podfile
